CREATE DATABASE IF NOT EXISTS tp_db;
CREATE USER IF NOT EXISTS 'tp_user'@'%' IDENTIFIED BY 'tp_password';
GRANT ALL PRIVILEGES ON tp_db.* TO 'tp_user'@'%';
FLUSH PRIVILEGES;
USE tp_db;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE
);

