Vagrant.configure("2") do |config|

  # VM 1 (db-server) 
  config.vm.define "db-server" do |db|
    db.vm.box = "bento/debian-13"
    db.vm.hostname = "db-server"
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    db.vm.provision "shell", path: "./db_server/db_server_provision.sh"
  end

  # VM 2 web-server 
  config.vm.define "web-server" do |web|
    web.vm.box = "bento/debian-13"
    web.vm.hostname = "web-server"
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    web.vm.synced_folder "./shared", "/var/www/html"
    web.vm.provision "shell", path: "./web_server/web_server_provision.sh"
    
  end

end

 
    ##### Options  #########################################################################################################    
    # config.vm.hdd = "20GB" --> si non instancié, espace dynamique gérer par le provider
    ##Taille maximale du disque - nécessite VBoxManage via vb.customize
    # vb.customize ['modifyhd', :id, '--resize', 20480]
    ##Activer l'accélération 3D (intéressant pour certains usages GUI)
    # vb.customize ['modifyvm', :id, '--accelerate3d', 'on']
    ## force le démarrage en mode GUI
    # vb.gui = true
    ## détruit l’état sauvegardé d’une VM à chaque arrêt (comme une « machine rebootant proprement à neuf »)
    # vb.customize ['modifyvm', :id, '--discardstate', 'on']
    ########################################################################################################################
