-- db/init.sql
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

GRANT ALL PRIVILEGES ON test.* TO 'user_test'@'%';
FLUSH PRIVILEGES;
